using System.Linq;
using System.Collections.Generic;
namespace D_OS_Save_Editor
{
    public class DataTable
    {
        public const string SupportedGameVersion = "2.0.119.430";

        public enum Attributes
        {
            Strength = 0,
            Dexerity,
            Intelligence,
            Consitution,
            Speed,
            Perception
        }

        public enum Abilities
        {
            ManAtArms = 0,
            ExpertMarksman,
            Scoundrel,
            SingleHanded,
            TwoHanded,
            Tenebrium,
            Bow,
            Crossbow,
            ShieldSpecialist,
            PlaceHolder_2,
            ArmourSpecialist,
            Witchcraft,
            Telekinesis,
            Willpower,
            Pyrokinetic,
            Hydrosophist,
            Aerotheurge,
            Geomancer,
            Blacksmithing,
            Sneaking,
            Pickpocketing,
            Lockpicking,
            Loremaster,
            Crafting,
            Bartering,
            PlaceHolder_3,
            PlaceHolder_4,
            PlaceHolder_5,
            Charisma,
            Leadership,
            LuckyCharm,
            BodyBuilding,
            DualWielding,
            Wand
        }

        public static string[] TalentNamesEffects =
        {
            "惊吓",
            "惊吓提升你的念力能力。",
            "工匠",
            "工匠提升你酿造药水、准备食物、书写卷轴的能力……",
            "侧击者",
            "侧击者消除你在被夹击时的防御惩罚。",
            "机会主义者",
            "机会主义者使你能够进行借机攻击。",
            "刺客",
            "刺客允许你使用匕首以外的武器背刺敌人。",
            "商人舌",
            "商人舌提升你的议价技巧。",
            "夜盗",
            "夜盗提升你的开锁能力。",
            "射手",
            "射手提升你在战斗中使用远程武器命中敌人的几率。",
            "角斗士",
            "角斗士提升你在战斗中使用近战武器命中敌人的几率。",
            "军阀",
            "军阀使总伤害提高 10%。",
            "飞毛腿",
            "飞毛腿使你的最大行动点数增加 1。",
            "红润脸颊",
            "红润脸颊使你的最大行动点数增加 1。",
            "杀手本能",
            "杀手本能使你的暴击几率提高 5%。",
            "坚不可摧",
            "坚不可摧提高你的护甲等级。",
            "远视",
            "远视使你远视，远程攻击在远距离精准，但近距离不精准。",
            "勇敢的心",
            "勇敢的心使你的恐惧抗性提高 25%。",
            "坚守阵地 2",
            "坚守阵地使你的击倒抗性提高 25%。",
            "避雷针 2",
            "避雷针使你的眩晕抗性提高 25%。",
            "米特拉达梯",
            "米特拉达梯使你的毒素抗性提高 25%。",
            "银舌",
            "银舌使你的沉默抗性提高 25%。（沉默时无法施法，直到效果结束。）",
            "不死小强",
            "当敌人打出致命一击时，只要你剩余生命大于 1，不死小强会使你保留 1 点生命。",
            "驮骡",
            "驮骡使你的负重翻倍。",
            "投掷",
            "投掷增加你可以投掷物体的最大重量和投掷距离。",
            "油脂猴",
            "油脂猴提高你修理损坏物品的能力。",
            "机智",
            "机智使你的经验获取速度提高 10%。",
            "更大更好",
            "更大更好使你获得 1 个额外的属性点。",
            "全能高手",
            "全能高手使你获得 2 个额外能力点。",
            "我的宝贝",
            "我的宝贝使你在每次攻击或受击时，装备有 50% 概率不损失耐久度。",
            "第六感",
            "第六感提高你发现（隐藏）事物的能力，无论是否在战斗中。",
            "健康形象 2",
            "健康形象 2 使你的总生命值提高 20%。",
            "纵火狂",
            "纵火狂提高你施放火系法术的能力。",
            "雨人",
            "雨人提高你施放水系法术的能力。",
            "暴风",
            "暴风提高你施放风系法术的能力。",
            "地卜师",
            "地卜师提高你施放土系法术的能力。",
            "迷人王子",
            "迷人王子提高你在对话中魅惑他人的能力。",
            "威吓者",
            "威吓者提高你在对话中威吓他人的能力。",
            "修辞学家",
            "修辞学家提高你在对话中说理的能力。",
            "幸运宠儿",
            "幸运宠儿提高你的总体运气。",
            "头狼",
            "头狼使你在战斗开始时的先攻提高 5。",
            "彩排",
            "彩排减少在战斗中装备不同物品所需的行动点。",
            "猫步",
            "猫步使你进行可疑行为时更不易被发现。",
            "宠物伙伴",
            "宠物伙伴使你能够与动物交谈。",
            "逃跑专家",
            "逃跑专家使你即使在敌人紧邻时也能逃离战斗。",
            "坚守阵地",
            "具有坚守阵地的角色不会被击倒。",
            "游击",
            "游击使潜行时的攻击伤害提高 50%。",
            "轻步",
            "轻步使你在发现陷阱和秘密时获得 +2 感知加成。",
            "早起的人",
            "复活时恢复全部生命值。",
            "能工巧匠",
            "能工巧匠使你在锻造和手艺中各获得 1 个奖励点。",
            "玻璃大炮",
            "玻璃大炮提供 4 点额外恢复行动点，但总生命值减少 50%。",
            "故作聪明",
            "故作聪明使所有人对你的态度降低 20，但智力增加 1 点。",
            "真刺激",
            "真刺激在你生命值低于 30% 时，回合行动点和最大行动点增加 2。",
            "天才法师",
            "天才法师使法术和卷轴的射程增加 2 米。",
            "水蛭",
            "水蛭使你在站在血泊中时回复生命。",
            "元素亲和",
            "元素亲和使你在站在同元素地表上时，法术行动点消耗减少 1。",
            "五星大厨",
            "五星大厨使食物的效果翻倍。",
            "恶霸",
            "恶霸对减速、残废或击倒的敌人造成的非魔法攻击提高 50%。",
            "元素游侠",
            "箭矢会根据目标所在的地表造成额外的元素伤害。",
            "避雷针",
            "避雷针使你免疫眩晕。",
            "政客",
            "政客使你的魅力增加 2 点，但智力减少 1 点。",
            "防风雨",
            "防风雨使你免疫环境效果。",
            "独狼",
            "具有独狼的角色无法拥有同伴，但基础生命值提高 70%，回合行动点和最大行动点增加 2，升级时获得额外能力点。",
            "僵尸",
            "僵尸使你从毒素中回复生命，但普通治疗会造成伤害。",
            "恶魔",
            "恶魔角色额外获得 15% 火焰抗性，但减少 15% 水系抗性。此外，最大火焰抗性提高 10。",
            "冰王",
            "冰王角色额外获得 15% 水系抗性，但减少 15% 火焰抗性。此外，最大水系抗性提高 10。",
            "勇气",
            "勇气使你对恐惧免疫，但无法逃离战斗。",
            "健谈法师",
            "健谈法师使你免疫沉默。",
            "扛过去",
            "扛过去将使体质豁免检定的状态效果持续时间减少一回合。",
            "速爬者",
            "速爬者角色在潜行时以正常速度移动。",
            "巨蟒",
            "巨蟒使你的 crushing 武器伤害提高 10%。",
            "臭气熏天",
            "臭气熏天使所有人对你的态度降低 25，但近战敌人在战斗中会觉得你更不具吸引力。",
            "启动器",
            "启动器角色会在游戏过程中发现某些秘密。",
            "厚皮",
            "厚皮使你的额外护甲等于你的战场技艺能力 + 5。",
            "健康形象",
            "健康形象使你的额外生命值等于战场技艺等级的 3%。",
            "铁皮",
            "铁皮使你的额外元素抗性等于战场技艺等级的 3%。",
            "箭矢回收",
            "箭矢回收使你有 33% 几率在射出特殊箭矢后回收它。",
            "闪避",
            "闪避使你的闪避几率提高 10%。",
            "速射",
            "速射使弓和弩的攻击范围增加 1 米。",
            "匕首大师",
            "匕首大师使匕首和刀的使用成本减少 1 行动点。",
            "背刺",
            "背刺允许角色使用匕首、刀、圆盾和刺剑进行背刺。",
            "健步如飞",
            "健步如飞使你的移动速度提高 10%。",
            "顽固",
            "顽固使你对冰冻、眩晕、石化和击倒的抗性提高 20%。",
            "回避机会主义者",
            "回避机会主义者使你能够躲避借机攻击。",
            "弹弓",
            "弹弓使你的手雷投掷距离增加 5 米。",
            "定位",
            "有了定位，你的手雷投掷将永不偏离。",
            "魔术师",
            "使你的魔杖技能获得额外一次使用。",
            "招架大师",
            "招架大师在双持时提供 10% 格挡几率。"
        };

        public static bool[] TalentIsHidden =
        {
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        };

        public static string[] Skills =
        {

        };

        /// <summary>
        /// Names used for Gold category items
        /// </summary>
        public static readonly string[] GoldNames =
            {"small_gold", "inbetween_gold", "trader_large_gold", "trader_insane_gold"};

        /// <summary>
        /// Names used for Arrow category items. Arrow items have prefix WPN which is shared with the Weapon category. Therefore, we need these strings to identify the Arrow category.
        /// </summary>
        public static readonly string[] ArrowTypeNames = {"arrow", "arrowhead", "arrowshaft"};

        public static string[] TraitNames =
        {
            "宽容",
            "记仇",
            "勇敢",
            "谨慎",
            "无私",
            "自私",
            "独立",
            "顺从",
            "务实",
            "浪漫",
            "精神",
            "物质",
            "正直",
            "叛逆",
            "直率",
            "体贴",
            "同情",
            "冷酷"
        };

        public static string[] TraitEffects =
        {
            "免疫诅咒",
            "借机攻击命中率 +20%",
            "先攻 +1",
            "潜行 +1",
            "声望 +2",
            "交易 +1",
            "意志力 +1",
            "当有领导力的队友在视野中时，意志力 +1（若队友领导力为 5 或更高，则 +2）",
            "工艺 +1",
            "幸运 +1",
            "免疫恐惧",
            "博学 +1",
            "领导力 +1",
            "偷窃 +1",
            "免疫魅惑",
            "魅力 +1",
            "暴击几率 +3%",
            "背刺命中率 +20%"
        };

        public static string[] GenerationBoostsFilterNames =
        {
            "armor",
            "weapon",
            "amulet",
            "belt",
            "body",
            "garment",
            "gloves",
            "shoes",
            "helmet",
            "ring",
            "shield",
            "axe",
            "bow",
            "club",
            "knife",
            "spear",
            "sword",
            "staff",
            "wand",
            "2h",
            "wpn",
            "arm"
        };

        public static string[] GenerationBoosts =
        {
            "Armor__Amulet_Boost_Barter_Mod",
            "Armor__Amulet_Boost_Blackrock_Mod",
            "Armor__Amulet_Boost_Charisma_Mod",
            "Armor__Amulet_Boost_DEX_Mod",
            "Armor__Amulet_Boost_DEX_Mod_Large",
            "Armor__Amulet_Boost_HearingBoost_Mod",
            "Armor__Amulet_Boost_Initiative_Mod",
            "Armor__Amulet_Boost_INT _Mod_Large",
            "Armor__Amulet_Boost_INT_Mod",
            "Armor__Amulet_Boost_INT_Mod_Large",
            "Armor__Amulet_Boost_Loremaster_Mod",
            "Armor__Amulet_Boost_MuteImmunity",
            "Armor__Amulet_Boost_PoisonRes_Mod",
            "Armor__Amulet_Boost_PoisonRes_Mod_Large",
            "Armor__Amulet_Boost_ShadowRes_Mod",
            "Armor__Amulet_Boost_ShadowRes_Mod_Large",
            "Armor__Amulet_Boost_SightBoost_Mod",
            "Armor__Amulet_Boost_SPD_Mod_Large",
            "Armor__Amulet_Boost_STR_Mod",
            "Armor__Amulet_Boost_STR_Mod_Large",
            "Armor__Amulet_Boost_Value_Mod",
            "Armor__Amulet_Boost_VitalityBoost_Mod",
            "Armor__Amulet_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Amulet_Boost_VitalityBoost_Mod_LargeLate",
            "Armor__Amulet_Boost_VitalityBoost_Mod_Late",
            "Armor__Amulet_Boost_VitalityBoost_Mod_Mid",
            "Armor__AmuletBoost_Initiative_Mod_Late",
            "Armor__AmuletBoost_Initiative_Mod_Mid",
            "Armor__Armor_Boost_BleedingImmunityLeather",
            "Armor__Armor_Boost_BleedingImmunityLeather_Late",
            "Armor__Armor_Boost_BlindImmunity",
            "Armor__Armor_Boost_BurnContact_All",
            "Armor__Armor_Boost_BurnContactMail",
            "Armor__Armor_Boost_BurnContactPlate",
            "Armor__Armor_Boost_BurnImmunity_All",
            "Armor__Armor_Boost_BurnImmunityMail",
            "Armor__Armor_Boost_BurnImmunityPlate",
            "Armor__Armor_Boost_ChillContact",
            "Armor__Armor_Boost_CrippledImmunityBoots",
            "Armor__Armor_Boost_CrippledImmunityMail",
            "Armor__Armor_Boost_CrippledImmunityPlate",
            "Armor__Armor_Boost_CursedImmunityRobe",
            "Armor__Armor_Boost_CursedImmunityRobe_Late",
            "Armor__Armor_Boost_FearImmunityMail",
            "Armor__Armor_Boost_FearImmunityMail_Late",
            "Armor__Armor_Boost_FreezeContact_All",
            "Armor__Armor_Boost_FreezeContactMail",
            "Armor__Armor_Boost_FreezeContactPlate",
            "Armor__Armor_Boost_FreezeImmunityMail",
            "Armor__Armor_Boost_FreezeImmunityPlate",
            "Armor__Armor_Boost_KnockdownImmunity_All",
            "Armor__Armor_Boost_KnockdownImmunityMail",
            "Armor__Armor_Boost_KnockdownImmunityPlate",
            "Armor__Armor_Boost_MuteImmunity",
            "Armor__Armor_Boost_MuteImmunityRobe",
            "Armor__Armor_Boost_MuteImmunityRobe_Late",
            "Armor__Armor_Boost_PetrifiedImmunityMail",
            "Armor__Armor_Boost_PetrifiedImmunityPlate",
            "Armor__Armor_Boost_PoisonContact_All",
            "Armor__Armor_Boost_PoisonContactLeather",
            "Armor__Armor_Boost_PoisonImmunity_All",
            "Armor__Armor_Boost_PoisonImmunityLeather",
            "Armor__Armor_Boost_PoisonImmunityMail",
            "Armor__Armor_Boost_PoisonImmunityPlate",
            "Armor__Armor_Boost_SlowedImmunity",
            "Armor__Armor_Boost_StunContact_All",
            "Armor__Armor_Boost_StunContactMail",
            "Armor__Armor_Boost_StunContactPlate",
            "Armor__Armor_Boost_StunImmunityMail",
            "Armor__Armor_Boost_StunImmunityPlate",
            "Armor__Belt_Boost_BodyBuilding_Mod",
            "Armor__Belt_Boost_Bow_Mod",
            "Armor__Belt_Boost_Crafting_Mod",
            "Armor__Belt_Boost_Crossbow_Mod",
            "Armor__Belt_Boost_DEX_Mod",
            "Armor__Belt_Boost_Initiative_Mod",
            "Armor__Belt_Boost_Initiative_Mod_Late",
            "Armor__Belt_Boost_Initiative_Mod_Mid",
            "Armor__Belt_Boost_Lockpicking_Mod",
            "Armor__Belt_Boost_Repair_Mod",
            "Armor__Belt_Boost_Shield_Mod",
            "Armor__Belt_Boost_STR_Mod",
            "Armor__Belt_Boost_STR_Mod_Late",
            "Armor__Belt_Boost_TwoHanded_Mod",
            "Armor__Belt_Boost_XBow_Mod",
            "Armor__Body_Boost_AirRes_ModHuge",
            "Armor__Body_Boost_AirRes_ModLarge",
            "Armor__Body_Boost_AirRes_ModLargeMail",
            "Armor__Body_Boost_AirRes_ModLargePlate",
            "Armor__Body_Boost_AirRes_ModNormal",
            "Armor__Body_Boost_AirRes_ModNormal_Late",
            "Armor__Body_Boost_ArmorMastery_ModMail",
            "Armor__Body_Boost_ArmorMastery_ModPlate",
            "Armor__Body_Boost_CON_Mod",
            "Armor__Body_Boost_CON_Mod_Late",
            "Armor__Body_Boost_DEX_Mod",
            "Armor__Body_Boost_DEX_Mod_Late",
            "Armor__Body_Boost_EarthRes_ModHuge",
            "Armor__Body_Boost_EarthRes_ModLarge",
            "Armor__Body_Boost_EarthRes_ModLargeMail",
            "Armor__Body_Boost_EarthRes_ModLargePlate",
            "Armor__Body_Boost_EarthRes_ModNormal",
            "Armor__Body_Boost_EarthRes_ModNormal_Late",
            "Armor__Body_Boost_FireRes_ModHuge",
            "Armor__Body_Boost_FireRes_ModLarge",
            "Armor__Body_Boost_FireRes_ModLargeMail",
            "Armor__Body_Boost_FireRes_ModLargePlate",
            "Armor__Body_Boost_FireRes_ModNormal",
            "Armor__Body_Boost_FireRes_ModNormal_Late",
            "Armor__Body_Boost_INT_Mod",
            "Armor__Body_Boost_INT_Mod_Late",
            "Armor__Body_Boost_INT_ModRobe",
            "Armor__Body_Boost_Movement_ClothMod",
            "Armor__Body_Boost_Movement_ClothMod_Early",
            "Armor__Body_Boost_Movement_ClothMod_LargeMid",
            "Armor__Body_Boost_Movement_ClothMod_Late",
            "Armor__Body_Boost_Movement_ClothMod_Mid",
            "Armor__Body_Boost_Movement_Mod",
            "Armor__Body_Boost_Movement_Mod_Late",
            "Armor__Body_Boost_Movement_Mod_Mid",
            "Armor__Body_Boost_PER_Mod",
            "Armor__Body_Boost_PER_Mod_Late",
            "Armor__Body_Boost_Ranged",
            "Armor__Body_Boost_SPD_Mod",
            "Armor__Body_Boost_SPD_Mod_Late",
            "Armor__Body_Boost_STR_Mod",
            "Armor__Body_Boost_STR_Mod_Late",
            "Armor__Body_Boost_Value_Mod",
            "Armor__Body_Boost_VitalityBoost_Mod",
            "Armor__Body_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Body_Boost_VitalityBoost_Mod_LargeMid",
            "Armor__Body_Boost_VitalityBoost_Mod_Late",
            "Armor__Body_Boost_VitalityBoost_Mod_Mid",
            "Armor__Body_Boost_WaterRes_ModHuge",
            "Armor__Body_Boost_WaterRes_ModLarge",
            "Armor__Body_Boost_WaterRes_ModLargeMail",
            "Armor__Body_Boost_WaterRes_ModLargePlate",
            "Armor__Body_Boost_WaterRes_ModNormal",
            "Armor__Body_Boost_WaterRes_ModNormal_Late",
            "Armor__Garment_Boost_AirRes_Mod",
            "Armor__Garment_Boost_AirRes_ModCombo",
            "Armor__Garment_Boost_AirRes_ModLarge",
            "Armor__Garment_Boost_AirRes_ModLate",
            "Armor__Garment_Boost_AirRes_ModSmall",
            "Armor__Garment_Boost_BodyBuilding_Mod",
            "Armor__Garment_Boost_DEX_Mod",
            "Armor__Garment_Boost_DEX_ModLate",
            "Armor__Garment_Boost_EarthRes_Mod",
            "Armor__Garment_Boost_EarthRes_ModCombo",
            "Armor__Garment_Boost_EarthRes_ModLarge",
            "Armor__Garment_Boost_EarthRes_ModLate",
            "Armor__Garment_Boost_EarthRes_ModSmall",
            "Armor__Garment_Boost_FireRes_Mod",
            "Armor__Garment_Boost_FireRes_ModCombo",
            "Armor__Garment_Boost_FireRes_ModLarge",
            "Armor__Garment_Boost_FireRes_ModLate",
            "Armor__Garment_Boost_FireRes_ModSmall",
            "Armor__Garment_Boost_Initiative_Mod",
            "Armor__Garment_Boost_Initiative_Mod_Late",
            "Armor__Garment_Boost_Initiative_Mod_Mid",
            "Armor__Garment_Boost_INT_Mod",
            "Armor__Garment_Boost_INT_ModLate",
            "Armor__Garment_Boost_PoisonRes_Mod",
            "Armor__Garment_Boost_PoisonRes_ModLarge",
            "Armor__Garment_Boost_PoisonRes_ModLate",
            "Armor__Garment_Boost_PoisonRes_ModSmall",
            "Armor__Garment_Boost_ShadowRes_Mod",
            "Armor__Garment_Boost_ShadowRes_ModLarge",
            "Armor__Garment_Boost_STR_Mod",
            "Armor__Garment_Boost_STR_ModLate",
            "Armor__Garment_Boost_Value_Mod",
            "Armor__Garment_Boost_VitalityBoost_Mod",
            "Armor__Garment_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Garment_Boost_VitalityBoost_Mod_LargeMid",
            "Armor__Garment_Boost_VitalityBoost_Mod_Late",
            "Armor__Garment_Boost_VitalityBoost_Mod_Mid",
            "Armor__Garment_Boost_WaterRes_Mod",
            "Armor__Garment_Boost_WaterRes_ModCombo",
            "Armor__Garment_Boost_WaterRes_ModLarge",
            "Armor__Garment_Boost_WaterRes_ModLate",
            "Armor__Garment_Boost_WaterRes_ModSmall",
            "Armor__Garment_Boost_Willpower_Mod",
            "Armor__Gloves_Boost_Crafting_Mod",
            "Armor__Gloves_Boost_DEX_Mod",
            "Armor__Gloves_Boost_Initiative_Mod",
            "Armor__Gloves_Boost_Initiative_Mod_Late",
            "Armor__Gloves_Boost_Initiative_Mod_Mid",
            "Armor__Gloves_Boost_Lockpicking_Mod",
            "Armor__Gloves_Boost_Pickpocket_Mod",
            "Armor__Gloves_Boost_Ranged_Mod",
            "Armor__Gloves_Boost_Ranged_Xbow_Mod",
            "Armor__Gloves_Boost_Repair_Mod",
            "Armor__Gloves_Boost_SingleHanded_Mod",
            "Armor__Gloves_Boost_Telekinesis_Mod",
            "Armor__Gloves_Boost_Value_Mod",
            "Armor__Helmet_Boost_ArmorMastery_Mod",
            "Armor__Helmet_Boost_ArmorMastery_Mod_Late",
            "Armor__Helmet_Boost_CON_Mod",
            "Armor__Helmet_Boost_CON_Mod_Late",
            "Armor__Helmet_Boost_HearingBoost_Mod",
            "Armor__Helmet_Boost_Leadership_Mod",
            "Armor__Helmet_Boost_PER_Mod",
            "Armor__Helmet_Boost_SightBoost_Mod",
            "Armor__Helmet_Boost_Sneaking_Mod",
            "Armor__Helmet_Boost_Value_Mod",
            "Armor__Helmet_Boost_VitalityBoost_Mod",
            "Armor__Helmet_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor__Helmet_Boost_VitalityBoost_Mod_LargeLate",
            "Armor__Helmet_Boost_VitalityBoost_Mod_Late",
            "Armor__Helmet_Boost_VitalityBoost_Mod_Mid",
            "Armor__HelmetBoost_Initiative_Mod",
            "Armor__HelmetBoost_Initiative_Mod_Late",
            "Armor__HelmetBoost_Initiative_Mod_Mid",
            "Armor__Ring_Boost_Blackrock_Mod",
            "Armor__Ring_Boost_CON_Mod",
            "Armor__Ring_Boost_HearingBoost_Mod",
            "Armor__Ring_Boost_Lockpicking_Mod",
            "Armor__Ring_Boost_Loremaster_Mod",
            "Armor__Ring_Boost_Movement_Mod",
            "Armor__Ring_Boost_Movement_Mod_Large",
            "Armor__Ring_Boost_Movement_Mod_Medium",
            "Armor__Ring_Boost_Movement_Mod_Super",
            "Armor__Ring_Boost_PER_Mod",
            "Armor__Ring_Boost_Pickpocketing_Mod",
            "Armor__Ring_Boost_PoisonRes_Mod",
            "Armor__Ring_Boost_PoisonRes_Mod_Large",
            "Armor__Ring_Boost_ShadowRes_Mod",
            "Armor__Ring_Boost_ShadowRes_Mod_Large",
            "Armor__Ring_Boost_SightBoost_Mod",
            "Armor__Ring_Boost_SPD_Mod",
            "Armor__Ring_Boost_Telekinesis_Mod",
            "Armor__Ring_Boost_Value_Mod",
            "Armor__Shoes_Boost_ActionPoints_Mod",
            "Armor__Shoes_Boost_Air_Mod",
            "Armor__Shoes_Boost_Air_Mod_Large",
            "Armor__Shoes_Boost_Air_Mod_Mid",
            "Armor__Shoes_Boost_Air_Mod_Mid_Large",
            "Armor__Shoes_Boost_Air_ModLarge",
            "Armor__Shoes_Boost_Barter_Mod",
            "Armor__Shoes_Boost_Earth_Mod",
            "Armor__Shoes_Boost_Earth_Mod_Large",
            "Armor__Shoes_Boost_Earth_Mod_Mid",
            "Armor__Shoes_Boost_Earth_Mod_Mid_Large",
            "Armor__Shoes_Boost_Earth_ModLarge",
            "Armor__Shoes_Boost_Fire_Mod",
            "Armor__Shoes_Boost_Fire_Mod_Large",
            "Armor__Shoes_Boost_Fire_Mod_Mid",
            "Armor__Shoes_Boost_Fire_Mod_Mid_Large",
            "Armor__Shoes_Boost_Fire_ModLarge",
            "Armor__Shoes_Boost_Initiative_Mod",
            "Armor__Shoes_Boost_Initiative_Mod_Late",
            "Armor__Shoes_Boost_Initiative_Mod_Mid",
            "Armor__Shoes_Boost_Luck_Mod",
            "Armor__Shoes_Boost_Movement_Mod",
            "Armor__Shoes_Boost_Movement_Mod_Large",
            "Armor__Shoes_Boost_Movement_Mod_Medium",
            "Armor__Shoes_Boost_Movement_Mod_Super",
            "Armor__Shoes_Boost_Pickpocket_Mod",
            "Armor__Shoes_Boost_Sneaking_Mod",
            "Armor__Shoes_Boost_SnowBoots",
            "Armor__Shoes_Boost_SPD_Mod",
            "Armor__Shoes_Boost_Value_Mod",
            "Armor__Shoes_Boost_VitalityBoost_Mod",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Huge",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Large",
            "Armor__Shoes_Boost_VitalityBoost_Mod_Large_Late",
            "Armor__Shoes_Boost_Water_Mod",
            "Armor__Shoes_Boost_Water_Mod_Large",
            "Armor__Shoes_Boost_Water_Mod_Mid",
            "Armor__Shoes_Boost_Water_Mod_Mid_Large",
            "Armor__Shoes_Boost_Water_ModLarge",
            "Armor_Belt_Boost_Bow",
            "Armor_Belt_Boost_DualWield",
            "Armor_Belt_Boost_PoisonRes_Mod",
            "Armor_Belt_Boost_PoisonRes_ModLarge",
            "Armor_Belt_Boost_PoisonRes_ModLate",
            "Armor_Belt_Boost_PoisonRes_ModSmall",
            "Armor_Belt_Boost_ShadowRes_Mod",
            "Armor_Belt_Boost_ShadowRes_ModLarge",
            "Armor_Belt_Boost_VitalityBoost_Mod",
            "Armor_Belt_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor_Belt_Boost_VitalityBoost_Mod_LargeLate",
            "Armor_Belt_Boost_VitalityBoost_Mod_Late",
            "Armor_Belt_Boost_VitalityBoost_Mod_Mid",
            "Armor_Body_Boost_BodyBuilding",
            "Armor_Body_Boost_Ranged",
            "Armor_Body_Boost_Ranged_Mod",
            "Armor_Body_Boost_Wands",
            "Armor_Body_Boost_Wands_Robe",
            "Armor_Boost_Amulet_Reflection_Air_Large",
            "Armor_Boost_Amulet_Reflection_Air_Legendary",
            "Armor_Boost_Amulet_Reflection_Air_Normal",
            "Armor_Boost_Amulet_Reflection_Earth_Large",
            "Armor_Boost_Amulet_Reflection_Earth_Legendary",
            "Armor_Boost_Amulet_Reflection_Earth_Normal",
            "Armor_Boost_Amulet_Reflection_Fire_Large",
            "Armor_Boost_Amulet_Reflection_Fire_Legendary",
            "Armor_Boost_Amulet_Reflection_Fire_Normal",
            "Armor_Boost_Amulet_Reflection_Water_Large",
            "Armor_Boost_Amulet_Reflection_Water_Legendary",
            "Armor_Boost_Amulet_Reflection_Water_Normal",
            "Armor_Boost_BurnContact_Ring",
            "Armor_Boost_DEX_Mod_Ring",
            "Armor_Boost_Dye_TOOL_Dye_Black",
            "Armor_Boost_Dye_TOOL_Dye_Blue",
            "Armor_Boost_Dye_TOOL_Dye_Candy",
            "Armor_Boost_Dye_TOOL_Dye_Gold",
            "Armor_Boost_Dye_TOOL_Dye_Green",
            "Armor_Boost_Dye_TOOL_Dye_Petrol",
            "Armor_Boost_Dye_TOOL_Dye_Purple",
            "Armor_Boost_Dye_TOOL_Dye_Red",
            "Armor_Boost_Dye_TOOL_Dye_Triad",
            "Armor_Boost_Dye_TOOL_Dye_White",
            "Armor_Boost_Dye_TOOL_Dye_Yellow",
            "Armor_Boost_FreezeContact_Ring",
            "Armor_Boost_Heal_CureWoundsKnight",
            "Armor_Boost_INT_Mod_Ring",
            "Armor_Boost_PoisonContact_Ring",
            "Armor_Boost_Projectile_BlitzBoltStartRing",
            "Armor_Boost_Projectile_BlitzBoltStartRingLate",
            "Armor_Boost_Projectile_FlareStartRing",
            "Armor_Boost_Projectile_FlareStartRingLate",
            "Armor_Boost_STR_Mod_Ring",
            "Armor_Boost_StunContact_Ring",
            "Armor_Boost_Target_Fortify",
            "Armor_Boost_Target_VampiricTouchRing",
            "Armor_Boost_Target_VampiricTouchRingLate",
            "Armor_Cone_WinterbreathMedium_Garment",
            "Armor_Gloves_Boost_VitalityBoost_Mod",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeEarly",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeLate",
            "Armor_Gloves_Boost_VitalityBoost_Mod_LargeLate ",
            "Armor_Gloves_Boost_VitalityBoost_Mod_Late",
            "Armor_Gloves_Boost_VitalityBoost_Mod_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large_Late",
            "Armor_Gloves_DefenseValue_ArmorBoost_Large_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal_Late",
            "Armor_Gloves_DefenseValue_ArmorBoost_Normal_Mid",
            "Armor_Gloves_DefenseValue_ArmorBoost_Small_Late",
            "Armor_Gloves_ReflectMelee",
            "Armor_Gloves_ReflectMelee_Large",
            "Armor_Heal_RegenerateStart_Garment",
            "Armor_Helmet_DefenseValue_Legendary_ArmorBoost",
            "Armor_Helmet_DefenseValue_Medium_ArmorBoost",
            "Armor_Helmet_Medium_ArmorDefense_Mod",
            "Armor_Helmet_Small_ArmorDefense_Mod",
            "Armor_Helmet_Target_Farsight",
            "Armor_Helmet_Target_TargetedPerception",
            "Armor_Large_AirResistance_Mod_Amulet",
            "Armor_Large_AirResistance_Mod_Amulet_Late",
            "Armor_Large_AirResistance_ModRing",
            "Armor_Large_AirResistance_ModRing_Late",
            "Armor_Large_ArmorDefense_Mod_LateMail",
            "Armor_Large_ArmorDefense_Mod_LatePlate",
            "Armor_Large_ArmorDefense_ModHelmet",
            "Armor_Large_EarthResistance_Mod_Amulet",
            "Armor_Large_EarthResistance_Mod_Amulet_Late",
            "Armor_Large_EarthResistance_ModRing",
            "Armor_Large_EarthResistance_ModRing_Late",
            "Armor_Large_FireResistance_Mod_Amulet",
            "Armor_Large_FireResistance_Mod_Amulet_Late",
            "Armor_Large_FireResistance_ModRing",
            "Armor_Large_FireResistance_ModRing_Late",
            "Armor_Large_WaterResistance_Mod_Amulet",
            "Armor_Large_WaterResistance_Mod_Amulet_Late",
            "Armor_Large_WaterResistance_ModRing",
            "Armor_Large_WaterResistance_ModRing_Late",
            "Armor_Legendary_ArmorDefense_ModMail",
            "Armor_Legendary_ArmorDefense_ModPlate",
            "Armor_Medium_ArmorDefense_ModMail",
            "Armor_Medium_ArmorDefense_ModMail_Late",
            "Armor_Medium_ArmorDefense_ModPlate",
            "Armor_Medium_ArmorDefense_ModPlate_Late",
            "Armor_Path_Firefly_Garment",
            "Armor_ReflectAll_Legendary",
            "Armor_ReflectMelee",
            "Armor_ReflectMelee_Large",
            "Armor_ReflectMelee_Large_Plate",
            "Armor_ReflectMelee_Plate",
            "Armor_Ring_Boost_BurnImmunity",
            "Armor_Ring_Boost_BurnImmunity_Late",
            "Armor_Ring_Boost_FreezeImmunity",
            "Armor_Ring_Boost_FreezeImmunity_Late",
            "Armor_Ring_Boost_PetrifiedImmunity",
            "Armor_Ring_Boost_PetrifiedImmunity_Late",
            "Armor_Ring_Boost_StunImmunity",
            "Armor_Ring_Boost_StunImmunity_Late",
            "Armor_Shield_Air_Amulet",
            "Armor_Shield_Earth_Amulet",
            "Armor_Shield_Fire_Amulet",
            "Armor_Shield_Water_Amulet",
            "Armor_Shoes_DefenseValue_ArmorBoost",
            "Armor_Shoes_DefenseValue_Large_ArmorBoost",
            "Armor_Shoes_DefenseValue_Legendary_ArmorBoost",
            "Armor_Shoes_DefenseValue_Medium_ArmorBoost",
            "Armor_Shoes_DefenseValue_Medium_ArmorBoost_Early",
            "Armor_Small_AirResistance_Mod",
            "Armor_Small_AirResistance_Mod_Amulet_Late",
            "Armor_Small_AirResistance_ModAmulet",
            "Armor_Small_AirResistance_ModAmulet_Large",
            "Armor_Small_AirResistance_ModRing",
            "Armor_Small_AirResistance_ModRing_Late",
            "Armor_Small_AirResistance_ModRingLarge",
            "Armor_Small_AllResist_Mod",
            "Armor_Small_ArmorDefense_ModLeather",
            "Armor_Small_ArmorDefense_ModMail",
            "Armor_Small_ArmorDefense_ModPlate",
            "Armor_Small_EarthResistance_Mod",
            "Armor_Small_EarthResistance_Mod_Amulet_Late",
            "Armor_Small_EarthResistance_ModAmulet",
            "Armor_Small_EarthResistance_ModAmulet_Large",
            "Armor_Small_EarthResistance_ModRing",
            "Armor_Small_EarthResistance_ModRing_Late",
            "Armor_Small_EarthResistance_ModRingLarge",
            "Armor_Small_FireResistance_Mod",
            "Armor_Small_FireResistance_Mod_Amulet_Late",
            "Armor_Small_FireResistance_ModAmulet",
            "Armor_Small_FireResistance_ModAmulet_Large",
            "Armor_Small_FireResistance_ModRing",
            "Armor_Small_FireResistance_ModRing_Late",
            "Armor_Small_FireResistance_ModRingLarge",
            "Armor_Small_Intelligence_Mod",
            "Armor_Small_Luck_Mod",
            "Armor_Small_Movement_Mod",
            "Armor_Small_Sneaking_Mod",
            "Armor_Small_Speed_Mod",
            "Armor_Small_Vitality_Mod",
            "Armor_Small_WaterResistance_Mod",
            "Armor_Small_WaterResistance_Mod_Amulet_Late",
            "Armor_Small_WaterResistance_ModAmulet",
            "Armor_Small_WaterResistance_ModAmulet_Large",
            "Armor_Small_WaterResistance_ModRing",
            "Armor_Small_WaterResistance_ModRing_Late",
            "Armor_Small_WaterResistance_ModRingLarge",
            "Armor_Summon_Undead_Garment",
            "Armor_Target_Immolate_Garment",
            "Armor_Target_InvisibilityTarget_Garment",
            "Armor_Target_PetrifyingTouch_Garment",
            "Armor_Target_PurifyingFire_Garment",
            "Armor_Teleportation_Resurrect_Garment",
            "Armor_Tornado_Air_Garment",
            "Armor_Unbreakable_Mod",
            "Armor_Unbreakable_Mod_Helmet",
            "Armor_Unbreakable_Mod_Plate",
            "Belt",
            "Shield_CrippledImmunity",
            "Shield_ElementalTortoise_Mod",
            "Shield_FreezeImmunity",
            "Shield_Giant_AirResistance_Mod",
            "Shield_Giant_EarthResistance_Mod",
            "Shield_Giant_FireResistance_Mod",
            "Shield_Giant_WaterResistance_Mod",
            "Shield_Large_AirResistance_Mod",
            "Shield_Large_Blocking_Mod",
            "Shield_Large_EarthResistance_Mod",
            "Shield_Large_FireResistance_Mod",
            "Shield_Large_WaterResistance_Mod",
            "Shield_LargeSingleHanded_Mod",
            "Shield_Legendary_AirResistance_Mod",
            "Shield_Legendary_EarthResistance_Mod",
            "Shield_Legendary_FireResistance_Mod",
            "Shield_Legendary_WaterResistance_Mod",
            "Shield_Medium_Blocking_Mod",
            "Shield_Medium_Blocking_Mod_Late",
            "Shield_Normal_AirResistance_Mod",
            "Shield_Normal_EarthResistance_Mod",
            "Shield_Normal_FireResistance_Mod",
            "Shield_Normal_Movement_Mod_Giant",
            "Shield_Normal_Movement_Mod_Large",
            "Shield_Normal_Movement_Mod_Medium",
            "Shield_Normal_WaterResistance_Mod",
            "Shield_PetrifiedImmunity",
            "Shield_Reflect_Melee_Air",
            "Shield_Reflect_Melee_Air_Large",
            "Shield_Reflect_Melee_Earth",
            "Shield_Reflect_Melee_Earth_Large",
            "Shield_Reflect_Melee_Fire",
            "Shield_Reflect_Melee_Fire_Large",
            "Shield_Reflect_Melee_Water",
            "Shield_Reflect_Melee_Water_Large",
            "Shield_ReflectMelee_Large",
            "Shield_ReflectMelee_Legendary",
            "Shield_ReflectMelee_Medium",
            "Shield_ReflectMelee_Small",
            "Shield_ReflectMelee_Small_Late",
            "Shield_Small_AirResistance_Mod",
            "Shield_Small_AirResistance_Mod_Late",
            "Shield_Small_Blocking_Mod",
            "Shield_Small_Blocking_Mod_Mid",
            "Shield_Small_Consitution_Mod",
            "Shield_Small_Durability_Mod",
            "Shield_Small_EarthResistance_Mod",
            "Shield_Small_EarthResistance_Mod_Late",
            "Shield_Small_FireResistance_Mod",
            "Shield_Small_FireResistance_Mod_Late",
            "Shield_Small_Luck_Mod",
            "Shield_Small_Movement_Mod",
            "Shield_Small_Movement_Mod_Large",
            "Shield_Small_Movement_Mod_Medium",
            "Shield_Small_ShadowResistance_Mod",
            "Shield_Small_WaterResistance_Mod",
            "Shield_Small_WaterResistance_Mod_Late",
            "Shield_Smallest_Blocking_Mod",
            "Shield_StunImmunity",
            "Shield_Unbreakable_Mod",
            "Shield_Value_Mod",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Air_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_APCost_ModXBow",
            "Weapon_Blackrock_Boost_Combo",
            "Weapon_Bleeding_Large_WeaponBoost_All",
            "Weapon_Bleeding_Large_WeaponBoost_Axe",
            "Weapon_Bleeding_Large_WeaponBoost_Bow",
            "Weapon_Bleeding_Large_WeaponBoost_Knife",
            "Weapon_Bleeding_Large_WeaponBoost_Spear",
            "Weapon_Bleeding_Large_WeaponBoost_Sword",
            "Weapon_Bleeding_Large_WeaponBoost_Xbow",
            "Weapon_Bleeding_WeaponBoost_Axe",
            "Weapon_Bleeding_WeaponBoost_Bow",
            "Weapon_Bleeding_WeaponBoost_Knife",
            "Weapon_Bleeding_WeaponBoost_Spear",
            "Weapon_Bleeding_WeaponBoost_Sword",
            "Weapon_Bleeding_WeaponBoost_Xbow",
            "Weapon_Blind_Large_WeaponBoost_All",
            "Weapon_Blind_Large_WeaponBoost_Staff",
            "Weapon_Blind_Large_WeaponBoost_Wand",
            "Weapon_Blind_WeaponBoost_Staff",
            "Weapon_Blind_WeaponBoost_Wand",
            "Weapon_Cripple_Large_WeaponBoost_Axe_All",
            "Weapon_Cripple_Large_WeaponBoost_Axe_Late",
            "Weapon_Cripple_Large_WeaponBoost_Club_Late",
            "Weapon_Cripple_Large_WeaponBoost_Staff_Late",
            "Weapon_Cripple_Large_WeaponBoost_Sword_Late",
            "Weapon_Cripple_WeaponBoost_Axe",
            "Weapon_Cripple_WeaponBoost_Club",
            "Weapon_Cripple_WeaponBoost_Staff",
            "Weapon_Cripple_WeaponBoost_Sword",
            "Weapon_Crit_Giant_WeaponBoost",
            "Weapon_Crit_Giant_WeaponBoost_Late",
            "Weapon_Crit_Huge_WeaponBoost",
            "Weapon_Crit_Huge_WeaponBoost_Late",
            "Weapon_Crit_Inhuman_WeaponBoost",
            "Weapon_Cursed_Large_WeaponBoost_All",
            "Weapon_Cursed_Large_WeaponBoost_Staff",
            "Weapon_Cursed_Large_WeaponBoost_Wand",
            "Weapon_Cursed_WeaponBoost_Staff",
            "Weapon_Cursed_WeaponBoost_Wand",
            "Weapon_Damage_Mod_Axe",
            "Weapon_Damage_Mod_Club",
            "Weapon_Damage_Mod_ModKnife",
            "Weapon_Damage_Mod_Sword",
            "Weapon_Damage_Mod_Wand",
            "Weapon_Diseased_Large_WeaponBoost_Knife",
            "Weapon_Diseased_Large_WeaponBoost_Spear",
            "Weapon_Diseased_WeaponBoost_Knife",
            "Weapon_Diseased_WeaponBoost_Spear",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Earth_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_Fear_Mod_Axe",
            "Weapon_Fear_Mod_Spear",
            "Weapon_Fear_Mod_Sword",
            "Weapon_FearLarge_Mod_All",
            "Weapon_FearLarge_Mod_Axe",
            "Weapon_FearLarge_Mod_Spear",
            "Weapon_FearLarge_Mod_Sword",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Fire_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_Fortification_Mod_Axe",
            "Weapon_Fortification_Mod_Club",
            "Weapon_Fortification_Mod_Spear",
            "Weapon_Fortification_Mod_Sword",
            "Weapon_Giant_AirDamage_ModAxe",
            "Weapon_Giant_AirDamage_ModAxe_Late",
            "Weapon_Giant_AirDamage_ModBow",
            "Weapon_Giant_AirDamage_ModBow_Late",
            "Weapon_Giant_AirDamage_ModClub",
            "Weapon_Giant_AirDamage_ModClub_Late",
            "Weapon_Giant_AirDamage_ModKnife",
            "Weapon_Giant_AirDamage_ModKnife_Late",
            "Weapon_Giant_AirDamage_ModSpear_Late",
            "Weapon_Giant_AirDamage_ModSword",
            "Weapon_Giant_AirDamage_ModSword_Late",
            "Weapon_Giant_AirDamage_ModXBow",
            "Weapon_Giant_AirDamage_ModXBow_Late",
            "Weapon_Giant_EarthDamage_ModAxe",
            "Weapon_Giant_EarthDamage_ModAxe_Late",
            "Weapon_Giant_EarthDamage_ModBow",
            "Weapon_Giant_EarthDamage_ModBow_Late",
            "Weapon_Giant_EarthDamage_ModClub",
            "Weapon_Giant_EarthDamage_ModClub_Late",
            "Weapon_Giant_EarthDamage_ModKnife",
            "Weapon_Giant_EarthDamage_ModKnife_Late",
            "Weapon_Giant_EarthDamage_ModSpear_Late",
            "Weapon_Giant_EarthDamage_ModSword",
            "Weapon_Giant_EarthDamage_ModSword_Late",
            "Weapon_Giant_EarthDamage_ModXBow",
            "Weapon_Giant_EarthDamage_ModXBow_Late",
            "Weapon_Giant_FireDamage_ModAxe",
            "Weapon_Giant_FireDamage_ModAxe_Late",
            "Weapon_Giant_FireDamage_ModBow",
            "Weapon_Giant_FireDamage_ModBow_Late",
            "Weapon_Giant_FireDamage_ModClub",
            "Weapon_Giant_FireDamage_ModClub_Late",
            "Weapon_Giant_FireDamage_ModKnife",
            "Weapon_Giant_FireDamage_ModKnife_Late",
            "Weapon_Giant_FireDamage_ModSpear_Late",
            "Weapon_Giant_FireDamage_ModSword",
            "Weapon_Giant_FireDamage_ModSword_Late",
            "Weapon_Giant_FireDamage_ModXBow",
            "Weapon_Giant_FireDamage_ModXBow_Late",
            "Weapon_Giant_Vitality_Mod_Late",
            "Weapon_Giant_Vitality_Mod_Mid",
            "Weapon_Giant_WaterDamage_ModAxe",
            "Weapon_Giant_WaterDamage_ModAxe_Late",
            "Weapon_Giant_WaterDamage_ModBow",
            "Weapon_Giant_WaterDamage_ModBow_Late",
            "Weapon_Giant_WaterDamage_ModClub",
            "Weapon_Giant_WaterDamage_ModClub_Late",
            "Weapon_Giant_WaterDamage_ModKnife",
            "Weapon_Giant_WaterDamage_ModKnife_Late",
            "Weapon_Giant_WaterDamage_ModSpear_Late",
            "Weapon_Giant_WaterDamage_ModSword",
            "Weapon_Giant_WaterDamage_ModSword_Late",
            "Weapon_Giant_WaterDamage_ModXBow",
            "Weapon_Giant_WaterDamage_ModXBow_Late",
            "Weapon_Huge_Damage_Mod_2H",
            "Weapon_Huge_Damage_Mod_Axe",
            "Weapon_Huge_Damage_Mod_Club",
            "Weapon_Huge_Damage_Mod_Sword",
            "Weapon_Huge_Damage_Mod_Wand",
            "Weapon_Huge_Damage_ModKnife",
            "Weapon_Knockdown_Mod",
            "Weapon_Knockdown_Mod_Large",
            "Weapon_Large_AirDamage_ModAxe",
            "Weapon_Large_AirDamage_ModAxe_Late",
            "Weapon_Large_AirDamage_ModBow",
            "Weapon_Large_AirDamage_ModBow_Late",
            "Weapon_Large_AirDamage_ModClub",
            "Weapon_Large_AirDamage_ModClub_Late",
            "Weapon_Large_AirDamage_ModKnife",
            "Weapon_Large_AirDamage_ModKnife_Late",
            "Weapon_Large_AirDamage_ModSpear",
            "Weapon_Large_AirDamage_ModSpear_Late",
            "Weapon_Large_AirDamage_ModSword",
            "Weapon_Large_AirDamage_ModSword_Late",
            "Weapon_Large_AirDamage_ModXBow",
            "Weapon_Large_AirDamage_ModXBow_Late",
            "Weapon_Large_Crit_Mod_Early",
            "Weapon_Large_Crit_Mod_Late",
            "Weapon_Large_Damage_Mod",
            "Weapon_Large_Damage_Mod_2H",
            "Weapon_Large_Damage_Mod_Axe",
            "Weapon_Large_Damage_Mod_Club",
            "Weapon_Large_Damage_Mod_Sword",
            "Weapon_Large_Damage_Mod_Wand",
            "Weapon_Large_Damage_ModKnife",
            "Weapon_Large_EarthDamage_ModAxe",
            "Weapon_Large_EarthDamage_ModAxe_Late",
            "Weapon_Large_EarthDamage_ModBow",
            "Weapon_Large_EarthDamage_ModBow_Late",
            "Weapon_Large_EarthDamage_ModClub",
            "Weapon_Large_EarthDamage_ModClub_Late",
            "Weapon_Large_EarthDamage_ModKnife",
            "Weapon_Large_EarthDamage_ModKnife_Late",
            "Weapon_Large_EarthDamage_ModSpear",
            "Weapon_Large_EarthDamage_ModSpear_Late",
            "Weapon_Large_EarthDamage_ModSword",
            "Weapon_Large_EarthDamage_ModSword_Late",
            "Weapon_Large_EarthDamage_ModXBow",
            "Weapon_Large_EarthDamage_ModXBow_Late",
            "Weapon_Large_FireDamage_ModAxe",
            "Weapon_Large_FireDamage_ModAxe_Late",
            "Weapon_Large_FireDamage_ModBow",
            "Weapon_Large_FireDamage_ModBow_Late",
            "Weapon_Large_FireDamage_ModClub",
            "Weapon_Large_FireDamage_ModClub_Late",
            "Weapon_Large_FireDamage_ModKnife",
            "Weapon_Large_FireDamage_ModKnife_Late",
            "Weapon_Large_FireDamage_ModSpear",
            "Weapon_Large_FireDamage_ModSpear_Late",
            "Weapon_Large_FireDamage_ModSword",
            "Weapon_Large_FireDamage_ModSword_Late",
            "Weapon_Large_FireDamage_ModXBow",
            "Weapon_Large_FireDamage_ModXBow_Late",
            "Weapon_Large_Luck_Mod",
            "Weapon_Large_Vitality_Mod",
            "Weapon_Large_WaterDamage_ModAxe",
            "Weapon_Large_WaterDamage_ModAxe_Late",
            "Weapon_Large_WaterDamage_ModBow",
            "Weapon_Large_WaterDamage_ModBow_Late",
            "Weapon_Large_WaterDamage_ModClub",
            "Weapon_Large_WaterDamage_ModClub_Late",
            "Weapon_Large_WaterDamage_ModKnife",
            "Weapon_Large_WaterDamage_ModKnife_Late",
            "Weapon_Large_WaterDamage_ModSpear",
            "Weapon_Large_WaterDamage_ModSpear_Late",
            "Weapon_Large_WaterDamage_ModSword",
            "Weapon_Large_WaterDamage_ModSword_Late",
            "Weapon_Large_WaterDamage_ModXBow",
            "Weapon_Large_WaterDamage_ModXBow_Late",
            "Weapon_Leadership_Mod",
            "Weapon_Legendary_Vitality_Mod_Axe",
            "Weapon_Legendary_Vitality_Mod_Club",
            "Weapon_Legendary_Vitality_Mod_Spear",
            "Weapon_Legendary_Vitality_Mod_Sword",
            "Weapon_Medium_Damage_Mod",
            "Weapon_Medium_Damage_Mod_Axe",
            "Weapon_Medium_Damage_Mod_Club",
            "Weapon_Medium_Damage_Mod_Sword",
            "Weapon_Medium_Damage_Mod_Wand",
            "Weapon_Medium_Vitality_Mod",
            "Weapon_Movement_Dagger_WeaponBoost_Huge_Late",
            "Weapon_Movement_Dagger_WeaponBoost_Large_Late",
            "Weapon_Movement_Dagger_WeaponBoost_Late",
            "Weapon_Mute_Large_WeaponBoost_All",
            "Weapon_Mute_Large_WeaponBoost_Staff",
            "Weapon_Mute_Large_WeaponBoost_Wand",
            "Weapon_Mute_WeaponBoost_Staff",
            "Weapon_Mute_WeaponBoost_Wand",
            "Weapon_Normal_Damage_Mod_2H",
            "Weapon_Petrify_Large_WeaponBoost_All",
            "Weapon_Petrify_Large_WeaponBoost_Spear",
            "Weapon_Petrify_Large_WeaponBoost_Staff",
            "Weapon_Petrify_Large_WeaponBoost_Wand",
            "Weapon_Petrify_WeaponBoost_Spear",
            "Weapon_Petrify_WeaponBoost_Staff",
            "Weapon_Petrify_WeaponBoost_Wand",
            "Weapon_Raged_WeaponBoost_Axe",
            "Weapon_Raged_WeaponBoost_Bow",
            "Weapon_Raged_WeaponBoost_Club",
            "Weapon_Raged_WeaponBoost_Knife",
            "Weapon_Raged_WeaponBoost_Spear",
            "Weapon_Raged_WeaponBoost_Sword",
            "Weapon_Raged_WeaponBoost_XBow",
            "Weapon_Ranged_BowMod",
            "Weapon_Ranged_XBowMod",
            "Weapon_Scope_Perception_Boost",
            "Weapon_SingleHanded_WeaponBoost_ModAxe",
            "Weapon_SingleHanded_WeaponBoost_ModClub",
            "Weapon_SingleHanded_WeaponBoost_ModSword",
            "Weapon_Small_ActionPoint_Mod",
            "Weapon_Small_AirDamage_Mod",
            "Weapon_Small_AirDamage_ModAxe",
            "Weapon_Small_AirDamage_ModBow",
            "Weapon_Small_AirDamage_ModClub",
            "Weapon_Small_AirDamage_ModKnife",
            "Weapon_Small_AirDamage_ModKnife_Late",
            "Weapon_Small_AirDamage_ModSpear",
            "Weapon_Small_AirDamage_ModSword",
            "Weapon_Small_AirDamage_ModXBow",
            "Weapon_Small_Consitution_Mod",
            "Weapon_Small_Consitution_Mod_Late",
            "Weapon_Small_Crit_Mod",
            "Weapon_Small_Damage_Mod",
            "Weapon_Small_Damage_Mod_2H",
            "Weapon_Small_Damage_Mod_ModKnife",
            "Weapon_Small_Dexterity_ModBow",
            "Weapon_Small_Dexterity_ModBow_Late",
            "Weapon_Small_Dexterity_ModCrossbow",
            "Weapon_Small_Dexterity_ModCrossbow_Late",
            "Weapon_Small_Dexterity_ModKnife",
            "Weapon_Small_Dexterity_ModKnife_Late",
            "Weapon_Small_Dexterity_ModSpear",
            "Weapon_Small_Dexterity_ModSpear_Late",
            "Weapon_Small_Durability_Mod",
            "Weapon_Small_EarthDamage_Mod",
            "Weapon_Small_EarthDamage_ModAxe",
            "Weapon_Small_EarthDamage_ModBow",
            "Weapon_Small_EarthDamage_ModClub",
            "Weapon_Small_EarthDamage_ModKnife",
            "Weapon_Small_EarthDamage_ModKnife_Late",
            "Weapon_Small_EarthDamage_ModSpear",
            "Weapon_Small_EarthDamage_ModSword",
            "Weapon_Small_EarthDamage_ModXBow",
            "Weapon_Small_FireDamage_Mod",
            "Weapon_Small_FireDamage_ModAxe",
            "Weapon_Small_FireDamage_ModBow",
            "Weapon_Small_FireDamage_ModClub",
            "Weapon_Small_FireDamage_ModKnife",
            "Weapon_Small_FireDamage_ModKnife_Late",
            "Weapon_Small_FireDamage_ModSpear",
            "Weapon_Small_FireDamage_ModSword",
            "Weapon_Small_FireDamage_ModXBow",
            "Weapon_Small_Intelligence_ModStaff",
            "Weapon_Small_Intelligence_ModStaff_Late",
            "Weapon_Small_Intelligence_ModStaffLarge",
            "Weapon_Small_Intelligence_ModStaffLarge_Late",
            "Weapon_Small_Intelligence_ModWand",
            "Weapon_Small_Intelligence_ModWand_Late",
            "Weapon_Small_Perception_Mod",
            "Weapon_Small_Perception_Mod_Late",
            "Weapon_Small_PoisonDamage_Mod",
            "Weapon_Small_Speed_Mod",
            "Weapon_Small_Speed_Mod_Late",
            "Weapon_Small_Strength_ModAxe",
            "Weapon_Small_Strength_ModAxe_Late",
            "Weapon_Small_Strength_ModClub",
            "Weapon_Small_Strength_ModClub_Late",
            "Weapon_Small_Strength_ModSword",
            "Weapon_Small_Strength_ModSword_Late",
            "Weapon_Small_TormentedSoul_Mod",
            "Weapon_Small_Value_Mod",
            "Weapon_Small_Vitality_Mod",
            "Weapon_Small_WaterDamage_Mod",
            "Weapon_Small_WaterDamage_ModAxe",
            "Weapon_Small_WaterDamage_ModBow",
            "Weapon_Small_WaterDamage_ModClub",
            "Weapon_Small_WaterDamage_ModKnife",
            "Weapon_Small_WaterDamage_ModKnife_Late",
            "Weapon_Small_WaterDamage_ModSpear",
            "Weapon_Small_WaterDamage_ModSword",
            "Weapon_Small_WaterDamage_ModXBow",
            "Weapon_TwoHanded_WeaponBoost_ModAxe",
            "Weapon_TwoHanded_WeaponBoost_ModSword",
            "Weapon_Unbreakable_Mod",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Axe",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Bow",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Club",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Crossbow",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Knife",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Spear",
            "Weapon_Water_Legendary_Skill_WeaponBoost_Sword",
            "Weapon_WillPower_Mod"
        };

        public static string[] StatsBoosts =
        {
            "Has_Reflection\tFalse"
        };

        /// <summary>
        /// Generation boosts that is new to GenerationBoosts but exists in Online resource
        /// </summary>
        public static string[] GenerationBoostsAddOnline;

        public static string[] StatsBoostsAddedOnline;

        /// <summary>
        /// All generation boosts found in user's savegame
        /// </summary>
        public static string[] UserGenerationBoosts = { };

        public static string[] UserStatsBoosts = { };

        public static Talent[] GetTalentArray()
        {
            var talents = new Talent[TalentNamesEffects.Length/2];

            for (var i = 0; i < TalentIsHidden.Length; i ++)
            {
                talents[i] = new Talent(i, TalentNamesEffects[i*2], TalentNamesEffects[i*2+1], TalentIsHidden[i]);
            }

            return talents;
        }

    /// <summary>
    /// Unified item classification for both backpack and add-item tabs
    /// </summary>
    public static ItemSortType GetItemSort(string statsName)
    {
        if (string.IsNullOrWhiteSpace(statsName))
            return ItemSortType.Other;

        var nameParts = statsName.ToLower().Split('_');

        // Handle "book_skill" prefix → Skillbook
        if (nameParts.Length >= 2 && nameParts[0] == "book" && nameParts[1] == "skill")
        {
            nameParts[0] = "skillbook";
            nameParts = new[] { "skillbook" }.Concat(nameParts.Skip(2)).ToArray();
        }

        // Handle "item" prefix → use the second part
        if (nameParts[0] == "item" && nameParts.Length >= 2)
            nameParts = nameParts.Skip(1).ToArray();

        string first = nameParts[0];
        ItemSortType result;

        switch (first)
        {
            case "item": result = ItemSortType.Item; break;
            case "potion": result = ItemSortType.Potion; break;
            case "arm": result = ItemSortType.Armor; break;
            case "wpn": result = ItemSortType.Weapon; break;
            case "skillbook": result = ItemSortType.Skillbook; break;
            case "scroll": result = ItemSortType.Scroll; break;
            case "grn": result = ItemSortType.Granade; break;
            case "food": result = ItemSortType.Food; break;
            case "con":
                if (nameParts.Length >= 2 && nameParts[1] == "potion")
                    result = ItemSortType.Potion;
                else
                    result = ItemSortType.Food;
                break;
            case "fur": result = ItemSortType.Furniture; break;
            case "loot": result = ItemSortType.Loot; break;
            case "quest": result = ItemSortType.Quest; break;
            case "tool": result = ItemSortType.Tool; break;
            case "unique": result = ItemSortType.Unique; break;
            case "book": result = ItemSortType.Book; break;
            default: result = ItemSortType.Other; break;
        }

        // Check for Gold type
        if (first == "gold" || System.Array.IndexOf(nameParts, "gold") >= 0)
            result = ItemSortType.Gold;

        // Check for arrow type
        if (first == "wpn" && nameParts.Length >= 2 && System.Array.IndexOf(ArrowTypeNames, nameParts[1]) >= 0)
            result = ItemSortType.Arrow;

        return result;
    }

        private static Dictionary<string, string> _boostDict;
        private static Dictionary<string, string> BoostDict
        {
            get
            {
                if (_boostDict == null)
                {
                    _boostDict = new Dictionary<string, string>
                    {
                        {"Armor", "护甲"},{"Amulet", "护符"},{"Belt", "腰带"},{"Body", "身体"},
                        {"Boots", "靴子"},{"Gloves", "手套"},{"Helmet", "头盔"},{"Ring", "戒指"},
                        {"Shield", "盾牌"},{"Weapon", "武器"},{"Garment", "外衣"},
                        {"Shoes", "靴子"},
                        {"Boost", "加成"},{"Mod", "附魔"},{"Large", "大型"},{"Small", "小型"},
                        {"DEX", "敏捷"},{"INT", "智力"},{"STR", "力量"},{"SPD", "速度"},
                        {"CON", "体质"},{"PER", "感知"},
                        {"Barter", "交易"},{"Charisma", "魅力"},{"Loremaster", "博学"},
                        {"PoisonRes", "毒抗"},{"FireRes", "火抗"},{"WaterRes", "水抗"},
                        {"EarthRes", "地抗"},{"AirRes", "电抗"},{"ShadowRes", "暗影抗性"},
                        {"Poison", "毒素"},{"Fire", "火焰"},{"Water", "水系"},{"Air", "雷电"},
                        {"Earth", "大地"},{"Shadow", "暗影"},{"Tenebrium", "黯金"},
                        {"Critical", "暴击"},{"Damage", "伤害"},{"Accuracy", "命中"},
                        {"Vitality", "生命"},{"Value", "价值"},
                        {"Initiative", "先攻"},{"SightBoost", "视野"},{"HearingBoost", "听觉"},
                        {"Strength", "力量"},{"Dexterity", "敏捷"},{"Intelligence", "智力"},
                        {"Speed", "速度"},{"Perception", "感知"},{"Constitution", "体质"},
                        {"Legendary", "传奇"},{"Epic", "史诗"},{"Rare", "稀有"},{"Unique", "独特"},
                        {"Skill", "技能"},{"WeaponBoost", "武器加成"},
                        {"Knife", "匕首"},{"Sword", "剑"},{"Spear", "矛"},{"Axe", "斧"},
                        {"Bow", "弓"},{"Staff", "法杖"},{"Wand", "魔杖"},{"Club", "锤"},
                        {"Crossbow", "弩"},{"2h", "双手"},
                        {"WillPower", "意志"},{"Willpower", "意志"},
                        {"Immunity", "免疫"},{"Resistance", "抗性"},
                        {"Mute", "沉默"},{"Charm", "魅惑"},{"Stun", "眩晕"},{"Cripple", "致残"},
                        {"Healing", "治疗"},{"Heal", "治疗"},{"HP", "生命"},{"AP", "行动点"},
                        {"Magic", "魔法"},{"Physical", "物理"},{"Bleeding", "流血"},
                        {"Haste", "加速"},{"Rage", "狂暴"},{"Regen", "回复"},{"Leech", "吸血"},
                        {"Thorns", "荆棘"},{"Retribution", "反击"},{"Block", "格挡"},
                        {"Dodge", "闪避"},{"Blocking", "格挡"},{"Reflect", "反射"},
                        {"Reflection", "反射"},{"ReflectMelee", "近战反射"},
                        {"ReflectAll", "全反射"},
                        {"Late", "后期"},{"Early", "早期"},{"Mid", "中期"},{"Huge", "极效"},
                        {"Giant", "巨型"},{"Medium", "中型"},{"Normal", "普通"},
                        {"Super", "超级"},{"Smallest", "最小"},
                        {"All", "全"},{"AllResistance", "全抗性"},{"AllStats", "全属性"},
                        {"AllResist", "全抗"},{"Random", "随机"},
                        {"Movement", "移动"},{"Dye", "染色"},{"Range", "射程"},
                        {"Scope", "瞄准镜"},{"Projectile", "投射物"},{"Cone", "锥形"},
                        {"Path", "路径"},{"Target", "目标"},
                        {"WaterDamage", "水系伤害"},{"EarthDamage", "大地伤害"},
                        {"FireDamage", "火焰伤害"},{"AirDamage", "雷电伤害"},
                        {"PoisonDamage", "毒素伤害"},
                        {"VitalityBoost", "生命加成"},{"ArmorBoost", "护甲加成"},
                        {"ArmorDefense", "护甲防御"},{"DefenseValue", "防御值"},
                        {"ArmorMastery", "护甲精通"},{"HelmetBoost", "头盔加成"},
                        {"AmuletBoost", "护符加成"},
                        {"Blackrock", "黯金"},
                        {"TOOL", "工具"},{"WPN", "武器"},
                        {"Sneaking", "潜行"},{"Pickpocket", "偷窃"},
                        {"Pickpocketing", "偷窃"},{"Lockpick", "开锁"},
                        {"Lockpicking", "开锁"},{"Repair", "修复"},
                        {"Crafting", "工艺"},{"Blacksmithing", "锻造"},
                        {"Luck", "幸运"},{"Leadership", "领导"},{"EXP", "经验"},
                        {"Gold", "金币"},{"Level", "等级"},{"Durability", "耐久"},
                        {"Melee", "近战"},{"Ranged", "远程"},
                        {"Elemental", "元素"},{"SingleHanded", "单手"},
                        {"TwoHanded", "双手"},{"DualWield", "双持"},
                        {"Dagger", "匕首"},{"Wands", "魔杖"},{"XBow", "弩"},
                        {"Cloth", "布甲"},{"Mail", "链甲"},{"Plate", "板甲"},
                        {"Robe", "长袍"},{"Leather", "皮甲"},
                        {"Hydrosophist", "水系"},{"Pyrokinetic", "火系"},
                        {"Geomancer", "地系"},{"Aerothurge", "气系"},
                        {"Witchcraft", "巫术"},{"ManAtArms", "战士"},
                        {"ExpertMarksman", "游侠"},{"Scoundrel", "恶棍"},
                        {"BodyBuilding", "体质"},
                        {"Petrify", "石化"},{"Petrified", "石化"},
                        {"Blind", "致盲"},{"Cursed", "诅咒"},{"Diseased", "患病"},
                        {"Raged", "激怒"},{"Fear", "恐惧"},{"Freeze", "冻结"},
                        {"Burn", "燃烧"},{"Chilled", "冻僵"},{"Slowed", "减速"},
                        {"Knockdown", "击倒"},{"Crippled", "残废"},
                        {"Contact", "接触"},{"PetrifyingTouch", "石化之触"},
                        {"FreezeContact", "冻结接触"},{"BurnContact", "燃烧接触"},
                        {"PoisonContact", "毒素接触"},{"StunContact", "眩晕接触"},
                        {"ChillContact", "冻僵接触"},
                        {"BurnImmunity", "火免"},{"FreezeImmunity", "冰免"},
                        {"StunImmunity", "眩晕免疫"},{"PoisonImmunity", "毒免"},
                        {"PetrifiedImmunity", "石化免疫"},{"FearImmunity", "恐惧免疫"},
                        {"MuteImmunity", "沉默免疫"},{"CrippledImmunity", "残废免疫"},
                        {"SlowedImmunity", "减速免疫"},{"KnockdownImmunity", "击倒免疫"},
                        {"BlindImmunity", "致盲免疫"},
                        {"BleedingImmunity", "流血免疫"},
                        {"CursedImmunityRobe", "诅咒免疫长袍"},
                        {"MuteImmunityRobe", "沉默免疫长袍"},
                        {"BleedingImmunityLeather", "流血免疫皮甲"},
                        {"PoisonImmunityLeather", "毒免皮甲"},
                        {"PoisonImmunityPlate", "毒免板甲"},
                        {"PoisonImmunityMail", "毒免链甲"},
                        {"BurnImmunityMail", "火免链甲"},
                        {"BurnImmunityPlate", "火免板甲"},
                        {"FreezeImmunityMail", "冰免链甲"},
                        {"FreezeImmunityPlate", "冰免板甲"},
                        {"StunImmunityMail", "眩晕免疫链甲"},
                        {"StunImmunityPlate", "眩晕免疫板甲"},
                        {"PetrifiedImmunityMail", "石化免疫链甲"},
                        {"PetrifiedImmunityPlate", "石化免疫板甲"},
                        {"FearImmunityMail", "恐惧免疫链甲"},
                        {"FearLarge", "大型恐惧"},
                        {"KnockdownImmunityMail", "击倒免疫链甲"},
                        {"KnockdownImmunityPlate", "击倒免疫板甲"},
                        {"CrippledImmunityMail", "残废免疫链甲"},
                        {"CrippledImmunityBoots", "残废免疫靴子"},
                        {"CrippledImmunityPlate", "残废免疫板甲"},
                        {"LargeEarly", "大型早期"},{"LargeLate", "大型后期"},
                        {"LargeMid", "大型中期"},{"LargeSingleHanded", "大型单手"},
                        {"LateMail", "后期链甲"},{"LatePlate", "后期板甲"},
                        {"ModKnife", "匕首附魔"},{"ModSword", "剑附魔"},
                        {"ModAxe", "斧附魔"},{"ModClub", "锤附魔"},
                        {"ModBow", "弓附魔"},{"ModXBow", "弩附魔"},
                        {"ModSpear", "矛附魔"},{"ModWand", "魔杖附魔"},
                        {"ModStaff", "法杖附魔"},{"ModCrossbow", "弩附魔"},
                        {"BowMod", "弓附魔"},{"XBowMod", "弩附魔"},
                        {"ModLarge", "大型附魔"},{"ModSmall", "小型附魔"},
                        {"ModHuge", "巨型附魔"},{"ModNormal", "普通附魔"},
                        {"ModLate", "后期附魔"},
                        {"ModAmulet", "护符附魔"},{"ModRing", "戒指附魔"},
                        {"ModRingLarge", "大型戒指附魔"},{"ModHelmet", "头盔附魔"},
                        {"ModCombo", "复合附魔"},
                        {"ModLargeMail", "大型链甲附魔"},{"ModLargePlate", "大型板甲附魔"},
                        {"ModStaffLarge", "大型法杖附魔"},{"ModRobe", "长袍附魔"},
                        {"ModLeather", "皮甲附魔"},{"ModMail", "链甲附魔"},
                        {"ModPlate", "板甲附魔"},{"ClothMod", "布甲附魔"},
                        {"WaterResistance", "水抗"},{"FireResistance", "火抗"},
                        {"AirResistance", "电抗"},{"EarthResistance", "地抗"},
                        {"ShadowResistance", "暗抗"},
                        {"Fortify", "强化"},{"Fortification", "城塞"},
                        {"Resurrect", "复活"},{"Immolate", "献祭"},
                        {"PurifyingFire", "洁净之火"},{"RegenerateStart", "再生"},
                        {"CureWoundsKnight", "骑士疗伤"},{"Unbreakable", "不破"},
                        {"TargetedPerception", "目标感知"},
                        {"ElementalTortoise", "元素龟甲"},
                        {"VampiricTouchRing", "吸血鬼之触戒指"},
                        {"VampiricTouchRingLate", "后期吸血鬼之触戒指"},
                        {"BlitzBoltStartRing", "闪电箭戒指"},
                        {"BlitzBoltStartRingLate", "后期闪电箭戒指"},
                        {"FlareStartRing", "闪光戒指"},
                        {"FlareStartRingLate", "后期闪光戒指"},
                        {"WinterbreathMedium", "中型冬日气息"},
                        {"Inhuman", "非人"},{"TormentedSoul", "受折磨之魂"},
                        {"Triad", "三合"},{"Candy", "糖果"},{"Petrol", "石油"},
                        {"Firefly", "萤火虫"},{"SnowBoots", "雪地靴"},
                        {"FreezeContactMail", "冻结接触链甲"},
                        {"FreezeContactPlate", "冻结接触板甲"},
                        {"BurnContactMail", "燃烧接触链甲"},
                        {"BurnContactPlate", "燃烧接触板甲"},
                        {"PoisonContactLeather", "毒素接触皮甲"},
                        {"StunContactMail", "眩晕接触链甲"},
                        {"StunContactPlate", "眩晕接触板甲"},
                        {"Blue", "蓝色"},{"Red", "红色"},{"Green", "绿色"},
                        {"White", "白色"},{"Black", "黑色"},{"Yellow", "黄色"},
                        {"Purple", "紫色"},{"Undead", "亡灵"},
                        {"Telekinesis", "念力"},{"Summon", "召唤"},
                        {"Teleportation", "传送"},{"Tornado", "龙卷风"},
                        {"Farsight", "远眺术"},{"ActionPoint", "行动点"},
                        {"ActionPoints", "行动点"},{"APCost", "行动消耗"},
                    };
                }
                return _boostDict;
            }
        }

        public static string TranslateBoostName(string boostName)
        {
            if (string.IsNullOrEmpty(boostName)) return boostName;
            var result = boostName;
            foreach (var kvp in BoostDict)
            {
                result = result.Replace(kvp.Key, kvp.Value);
            }
            result = result.Replace("__", "·").Replace("  ", "").Replace("_", "");
            return result;
        }
    }
}